<?php
declare(strict_types=1);
namespace App\Services; use App\Core\Database; use App\Repositories\ExpenseRepository;
final class ExpenseService {
 public function create(array $d,array $actor):int{$pdo=Database::connection();$pdo->beginTransaction();try{$this->assertRefs($pdo,(int)$d['user_id'],(int)$d['account_id'],(int)$d['category_id']);$id=(new ExpenseRepository())->create($d);if(($d['status']??'posted')==='posted')$this->applyBalance($pdo,(int)$d['account_id'],(int)$d['user_id'],-(float)$d['amount']);$this->audit($pdo,(int)$actor['id'],'create','expenses',$id,null,$d);$pdo->commit();return $id;}catch(\Throwable $e){$pdo->rollBack();throw $e;}}
 public function update(int $id,array $d,array $actor):void{$userId=(int)$actor['id'];$pdo=Database::connection();$pdo->beginTransaction();try{$old=(new ExpenseRepository())->findOwned($id,$userId);if(!$old)throw new \RuntimeException('Expense not found or not owned by you.');$this->assertRefs($pdo,$userId,(int)$d['account_id'],(int)$d['category_id']);if(($old['status']??'posted')==='posted')$this->applyBalance($pdo,(int)$old['account_id'],$userId,(float)$old['amount']);if(($d['status']??'posted')==='posted')$this->applyBalance($pdo,(int)$d['account_id'],$userId,-(float)$d['amount']);(new ExpenseRepository())->updateOwned($id,$d,$userId);$this->audit($pdo,$userId,'update','expenses',$id,$old,$d);$pdo->commit();}catch(\Throwable $e){$pdo->rollBack();throw $e;}}
 public function delete(int $id,array $actor):void{$userId=(int)$actor['id'];$pdo=Database::connection();$pdo->beginTransaction();try{$old=(new ExpenseRepository())->findOwned($id,$userId);if(!$old)throw new \RuntimeException('Expense not found or not owned by you.');(new ExpenseRepository())->deleteOwned($id,$userId);if(($old['status']??'posted')==='posted')$this->applyBalance($pdo,(int)$old['account_id'],$userId,(float)$old['amount']);$this->audit($pdo,$userId,'delete','expenses',$id,$old,null);$pdo->commit();}catch(\Throwable $e){$pdo->rollBack();throw $e;}}
 private function assertRefs($pdo,int $userId,int $accountId,int $categoryId):void{$a=$pdo->prepare('SELECT COUNT(*) FROM accounts WHERE id=? AND user_id=? AND status="active"');$a->execute([$accountId,$userId]);if((int)$a->fetchColumn()<1)throw new \RuntimeException('Invalid account for this user.');$c=$pdo->prepare('SELECT COUNT(*) FROM categories WHERE id=? AND status="active"');$c->execute([$categoryId]);if((int)$c->fetchColumn()<1)throw new \RuntimeException('Invalid category.');}
 private function applyBalance($pdo,int $accountId,int $userId,float $delta):void{$s=$pdo->prepare('UPDATE accounts SET current_balance=current_balance+?,updated_at=NOW() WHERE id=? AND user_id=?');$s->execute([$delta,$accountId,$userId]);if($s->rowCount()<1)throw new \RuntimeException('Unable to update account balance.');}
 private function audit($pdo,int $uid,string $action,string $entity,int $id,$old,$new):void{$s=$pdo->prepare('INSERT INTO audit_logs(user_id,action,entity,entity_id,old_values,new_values,ip_address,user_agent,created_at) VALUES(?,?,?,?,?,?,?,?,NOW())');$s->execute([$uid,$action,$entity,$id,$old?json_encode($old):null,$new?json_encode($new):null,$_SERVER['REMOTE_ADDR']??null,$_SERVER['HTTP_USER_AGENT']??null]);}
}
