<?php
declare(strict_types=1);
namespace App\Repositories; use App\Core\Database;
final class AccountRepository {
 public function allForUser(int $userId,bool $activeOnly=false,?int $page=null):array{$sql='SELECT a.*, COALESCE(a.current_balance,a.opening_balance) balance FROM accounts a WHERE a.user_id=?';if($activeOnly)$sql.=' AND a.status="active"';$sql.=' ORDER BY a.name,a.id';return \App\Core\Pagination::query($sql,[$userId],$page);}
 public function allVisible(array $actor,?int $page=null):array{if(\App\Services\Authorization::allows($actor,'finance.view_all')){return \App\Core\Pagination::query('SELECT a.*,u.name user_name,COALESCE(a.current_balance,a.opening_balance) balance FROM accounts a JOIN users u ON u.id=a.user_id ORDER BY u.name,a.name,a.id',[],$page);}return $this->allForUser((int)$actor['id'],false,$page);}
 public function findForUser(int $id,int $userId):?array{$s=Database::connection()->prepare('SELECT * FROM accounts WHERE id=? AND user_id=?');$s->execute([$id,$userId]);return $s->fetch()?:null;}
 public function create(array $d,int $userId):int{$opening=\App\Services\Amount::decimal(\App\Services\Amount::cents($d['opening_balance']??0,'opening_balance',true));$s=Database::connection()->prepare('INSERT INTO accounts(user_id,name,type,opening_balance,current_balance,description,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,NOW(),NOW())');$s->execute([$userId,trim((string)$d['name']),trim((string)$d['type']),$opening,$opening,$d['description']??null,$d['status']??'active']);return (int)Database::connection()->lastInsertId();}
 public function update(int $id,array $d,int $userId):void{$s=Database::connection()->prepare('UPDATE accounts SET name=?,type=?,description=?,status=?,updated_at=NOW() WHERE id=? AND user_id=?');$s->execute([trim((string)$d['name']),trim((string)$d['type']),$d['description']??null,$d['status']??'active',$id,$userId]);if(!$this->findForUser($id,$userId))throw new \RuntimeException('Account not found or not owned by you.');}
 public function delete(int $id,int $userId):void{$pdo=Database::connection();$used=$pdo->prepare('SELECT COUNT(*) FROM expenses WHERE account_id=? AND user_id=?');$used->execute([$id,$userId]);if((int)$used->fetchColumn()>0)throw new \RuntimeException('Accounts with expenses can be deactivated, not deleted.');$s=$pdo->prepare('DELETE FROM accounts WHERE id=? AND user_id=?');$s->execute([$id,$userId]);}
}
