<?php
declare(strict_types=1);
namespace App\Repositories; use App\Core\Database;
final class ExpenseRepository { public function paginate(array $f,int $page=1,int $per=10):array{$pdo=Database::connection();$where=['1=1'];$p=[];if(!empty($f['q'])){$where[]='(e.description LIKE ? OR e.notes LIKE ?)';$p[]='%'.$f['q'].'%';$p[]='%'.$f['q'].'%';}foreach(['category_id','account_id','user_id','status'] as $k){if(($f[$k]??'')!==''){$where[]='e.'.$k.'=?';$p[]=$f[$k];}}if(!empty($f['from'])){$where[]='e.expense_date>=?';$p[]=$f['from'];}if(!empty($f['to'])){$where[]='e.expense_date<=?';$p[]=$f['to'];}$cnt=$pdo->prepare('SELECT COUNT(*) FROM expenses e WHERE '.implode(' AND ',$where));$cnt->execute($p);$total=(int)$cnt->fetchColumn();$off=($page-1)*$per;$sql='SELECT e.*,c.name category_name,a.name account_name,u.name user_name FROM expenses e LEFT JOIN categories c ON c.id=e.category_id LEFT JOIN accounts a ON a.id=e.account_id LEFT JOIN users u ON u.id=e.user_id WHERE '.implode(' AND ',$where).' ORDER BY e.expense_date DESC,e.id DESC LIMIT '.(int)$per.' OFFSET '.(int)$off;$s=$pdo->prepare($sql);$s->execute($p);return ['rows'=>$s->fetchAll(),'total'=>$total,'page'=>$page,'per'=>$per];}
 public function find(int $id):?array{$s=Database::connection()->prepare('SELECT e.*,c.name category_name,a.name account_name,u.name user_name FROM expenses e LEFT JOIN categories c ON c.id=e.category_id LEFT JOIN accounts a ON a.id=e.account_id LEFT JOIN users u ON u.id=e.user_id WHERE e.id=?');$s->execute([$id]);return $s->fetch()?:null;}
 public function create(array $d):int{$s=Database::connection()->prepare('INSERT INTO expenses(user_id,amount,expense_date,category_id,account_id,description,notes,receipt_path,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,NOW(),NOW())');$s->execute([$d['user_id'],$d['amount'],$d['expense_date'],$d['category_id'],$d['account_id'],$d['description'],$d['notes']??null,$d['receipt_path']??null,$d['status']??'posted']);return (int)Database::connection()->lastInsertId();}
 public function update(int $id,array $d):void{$s=Database::connection()->prepare('UPDATE expenses SET amount=?,expense_date=?,category_id=?,account_id=?,description=?,notes=?,receipt_path=COALESCE(?,receipt_path),status=?,updated_at=NOW() WHERE id=?');$s->execute([$d['amount'],$d['expense_date'],$d['category_id'],$d['account_id'],$d['description'],$d['notes']??null,$d['receipt_path']??null,$d['status']??'posted',$id]);}
 public function delete(int $id):void{Database::connection()->prepare('DELETE FROM expenses WHERE id=?')->execute([$id]);}
}
