<?php
declare(strict_types=1);
namespace App\Repositories; use App\Core\Database;
final class ExpenseRepository {
 private function scope(array &$where,array &$p,array $actor):void{if(!in_array($actor['role_name']??'', ['Super Admin','Admin'], true)){$where[]='e.user_id=?';$p[]=(int)$actor['id'];}elseif(($actor['role_name']??'')==='Admin'){$where[]='COALESCE(r.name,"")<>"Super Admin"';}}
 public function paginate(array $f,array $actor,int $page=1,int $per=10):array{$pdo=Database::connection();$where=['1=1'];$p=[];$this->scope($where,$p,$actor);if(!empty($f['q'])){$where[]='(e.description LIKE ? OR e.notes LIKE ?)';$p[]='%'.$f['q'].'%';$p[]='%'.$f['q'].'%';}foreach(['category_id','account_id','user_id','status'] as $k){if(($f[$k]??'')!=='' && (in_array($k,['category_id','account_id','status'],true)||in_array($actor['role_name']??'', ['Super Admin','Admin'], true))){$where[]='e.'.$k.'=?';$p[]=$f[$k];}}if(!empty($f['from'])){$where[]='e.expense_date>=?';$p[]=$f['from'];}if(!empty($f['to'])){$where[]='e.expense_date<=?';$p[]=$f['to'];}$joins=' LEFT JOIN users u ON u.id=e.user_id LEFT JOIN user_roles ur ON ur.user_id=u.id LEFT JOIN roles r ON r.id=ur.role_id';$cnt=$pdo->prepare('SELECT COUNT(DISTINCT e.id) FROM expenses e'.$joins.' WHERE '.implode(' AND ',$where));$cnt->execute($p);$total=(int)$cnt->fetchColumn();$off=($page-1)*$per;$sql='SELECT e.*,c.name category_name,a.name account_name,u.name user_name,ucs.badge,COALESCE(ucs.icon,c.icon) category_icon,COALESCE(ucs.color,c.color) category_color FROM expenses e LEFT JOIN categories c ON c.id=e.category_id LEFT JOIN accounts a ON a.id=e.account_id LEFT JOIN user_category_settings ucs ON ucs.user_id=e.user_id AND ucs.category_id=e.category_id'.$joins.' WHERE '.implode(' AND ',$where).' GROUP BY e.id ORDER BY e.expense_date DESC,e.id DESC LIMIT '.(int)$per.' OFFSET '.(int)$off;$s=$pdo->prepare($sql);$s->execute($p);return ['rows'=>$s->fetchAll(),'total'=>$total,'page'=>$page,'per'=>$per];}
 public function findVisible(int $id,array $actor):?array{$where=['e.id=?'];$p=[$id];$this->scope($where,$p,$actor);$s=Database::connection()->prepare('SELECT e.*,c.name category_name,a.name account_name,u.name user_name,ucs.badge,COALESCE(ucs.icon,c.icon) category_icon,COALESCE(ucs.color,c.color) category_color FROM expenses e LEFT JOIN categories c ON c.id=e.category_id LEFT JOIN accounts a ON a.id=e.account_id LEFT JOIN users u ON u.id=e.user_id LEFT JOIN user_roles ur ON ur.user_id=u.id LEFT JOIN roles r ON r.id=ur.role_id LEFT JOIN user_category_settings ucs ON ucs.user_id=e.user_id AND ucs.category_id=e.category_id WHERE '.implode(' AND ',$where).' LIMIT 1');$s->execute($p);return $s->fetch()?:null;}
 public function findOwned(int $id,int $userId):?array{$s=Database::connection()->prepare('SELECT * FROM expenses WHERE id=? AND user_id=?');$s->execute([$id,$userId]);return $s->fetch()?:null;}
 public function create(array $d):int{$s=Database::connection()->prepare('INSERT INTO expenses(user_id,amount,expense_date,category_id,account_id,description,notes,receipt_path,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,NOW(),NOW())');$s->execute([$d['user_id'],$d['amount'],$d['expense_date'],$d['category_id'],$d['account_id'],$d['description'],$d['notes']??null,$d['receipt_path']??null,$d['status']??'posted']);return (int)Database::connection()->lastInsertId();}
 public function updateOwned(int $id,array $d,int $userId):void{$s=Database::connection()->prepare('UPDATE expenses SET amount=?,expense_date=?,category_id=?,account_id=?,description=?,notes=?,receipt_path=COALESCE(?,receipt_path),status=?,updated_at=NOW() WHERE id=? AND user_id=?');$s->execute([$d['amount'],$d['expense_date'],$d['category_id'],$d['account_id'],$d['description'],$d['notes']??null,$d['receipt_path']??null,$d['status']??'posted',$id,$userId]);if($s->rowCount()<1)throw new \RuntimeException('Expense not found or not owned by you.');}
 public function deleteOwned(int $id,int $userId):void{$s=Database::connection()->prepare('DELETE FROM expenses WHERE id=? AND user_id=?');$s->execute([$id,$userId]);if($s->rowCount()<1)throw new \RuntimeException('Expense not found or not owned by you.');}
}
