<?php
declare(strict_types=1);
namespace App\Repositories;
use App\Core\Database;
final class UserRepository {
 public function findByEmail(string $email):?array{$s=Database::connection()->prepare('SELECT * FROM users WHERE email=? LIMIT 1');$s->execute([$email]);return $s->fetch()?:null;}
 public function find(int $id):?array{$s=Database::connection()->prepare('SELECT * FROM users WHERE id=?');$s->execute([$id]);return $s->fetch()?:null;}
 public function findWithRole(int $id):?array{$pdo=Database::connection();$s=$pdo->prepare('SELECT u.*,r.name role_name FROM users u LEFT JOIN user_roles ur ON ur.user_id=u.id LEFT JOIN roles r ON r.id=ur.role_id WHERE u.id=? LIMIT 1');$s->execute([$id]);$u=$s->fetch();if(!$u)return null;$p=$pdo->prepare('SELECT p.name FROM permissions p JOIN role_permissions rp ON rp.permission_id=p.id JOIN user_roles ur ON ur.role_id=rp.role_id WHERE ur.user_id=?');$p->execute([$id]);$u['permissions']=array_column($p->fetchAll(),'name');return $u;}
 public function all(string $q='',int $page=1,int $per=10,array $actor=[]):array{$pdo=Database::connection();$where=[];$params=[];if(($actor['role_name']??'')==='Admin'){$where[]='COALESCE(r.name,"")<>"Super Admin"';}if($q!==''){$where[]='(u.name LIKE ? OR u.email LIKE ?)';$params=["%$q%","%$q%"];}$whereSql=$where?'WHERE '.implode(' AND ',$where):'';$cnt=$pdo->prepare('SELECT COUNT(DISTINCT u.id) FROM users u LEFT JOIN user_roles ur ON ur.user_id=u.id LEFT JOIN roles r ON r.id=ur.role_id '.$whereSql);$cnt->execute($params);$total=(int)$cnt->fetchColumn();$off=($page-1)*$per;$sql='SELECT u.*,GROUP_CONCAT(r.name SEPARATOR ", ") role_names FROM users u LEFT JOIN user_roles ur ON ur.user_id=u.id LEFT JOIN roles r ON r.id=ur.role_id '.$whereSql.' GROUP BY u.id ORDER BY u.created_at DESC LIMIT '.(int)$per.' OFFSET '.(int)$off;$s=$pdo->prepare($sql);$s->execute($params);return ['rows'=>$s->fetchAll(),'total'=>$total,'page'=>$page,'per'=>$per];}
 public function create(array $d):int{$pdo=Database::connection();$s=$pdo->prepare('INSERT INTO users(name,email,password_hash,status,created_at,updated_at) VALUES(?,?,?,?,NOW(),NOW())');$s->execute([trim((string)$d['name']),trim((string)$d['email']),password_hash((string)$d['password'],PASSWORD_DEFAULT),$d['status']??'active']);return (int)$pdo->lastInsertId();}
 public function update(int $id,array $d):void{$pdo=Database::connection();$sql='UPDATE users SET name=?,email=?,status=?,updated_at=NOW()';$params=[trim((string)$d['name']),trim((string)$d['email']),$d['status']];if(!empty($d['password'])){$sql.=',password_hash=?';$params[]=password_hash((string)$d['password'],PASSWORD_DEFAULT);} $params[]=$id;$pdo->prepare($sql.' WHERE id=?')->execute($params);}
 public function setRole(int $userId,int $roleId):void{$pdo=Database::connection();$pdo->prepare('DELETE FROM user_roles WHERE user_id=?')->execute([$userId]);$pdo->prepare('INSERT INTO user_roles(user_id,role_id) VALUES(?,?)')->execute([$userId,$roleId]);}
 public function roleNameById(int $roleId):?string{$s=Database::connection()->prepare('SELECT name FROM roles WHERE id=?');$s->execute([$roleId]);$v=$s->fetchColumn();return $v?:null;}
 public function roleIdByName(string $name):?int{$s=Database::connection()->prepare('SELECT id FROM roles WHERE name=? LIMIT 1');$s->execute([$name]);$id=$s->fetchColumn();return $id?(int)$id:null;}
 public function roles(array $actor=[]):array{$sql='SELECT * FROM roles';$p=[];if(($actor['role_name']??'')==='Admin'){$sql.=' WHERE name<>?';$p[]='Super Admin';}$sql.=' ORDER BY FIELD(name,"Super Admin","Admin","User")';$s=Database::connection()->prepare($sql);$s->execute($p);return $s->fetchAll();}
}
